name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: xcodebuild
      run: |
          xcodebuild -project SwiftyGameControllerExample.xcodeproj -scheme SwiftyGameController build
    - name: SPM
      run: |
        swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios12.1-simulator"


